/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eajjlsfplesitsrakpdu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhampsc2ZwbGVzaXRzcmFrcGR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NjAxNDgsImV4cCI6MjA3NzAzNjE0OH0.TW4XLfZ-pc85k0-ndrzkkT5B1KEqeDRxlR7Os2bw3vs"